### ISSUE TITLE
怎么使用这个小工具呢

### ISSUE THREAD

**Issue by jimmybasketball** [scruel/ClipIt#1]
怎么使用这个小工具呢？readme里面表示没得具体使用步骤哇。可以直接运行clipint.exe吗？提到的7牛云盘需要自己去申请吗？多谢

**Comment by scruel** [comment]
你好，是的，要自己去申请，具体步骤没几步呀，只要有 Java 环境，下载好后配下 KEY 就可以了
http://note.youdao.com/noteshare?id=ab721126eb70344c63b336c260263c2b&sub=FCE2356D616A4DCE89380B5EE1A98087
这是知乎上一位朋友写的，可以看看呢~

**Comment by jimmybasketball** [comment]
喝水不忘挖井人，打call！
